-- A single student user
CREATE TABLE IF NOT EXISTS students
(
    id        uuid DEFAULT gen_random_uuid() PRIMARY KEY UNIQUE NOT NULL,
    name      varchar(127)                                      NOT NULL,
    surname   varchar(128)                                      NOT NULL,
    email     varchar(100)                                      NOT NULL,
    pass_hash varchar(64)                                       NOT NULL
);

-- A single subject teacher
CREATE TABLE IF NOT EXISTS teachers
(
    id         uuid DEFAULT gen_random_uuid() PRIMARY KEY UNIQUE NOT NULL,
    name       varchar(127)                                      NOT NULL,
    surname    varchar(127)                                      NOT NULL,
    patronymic varchar(127)                                      NOT NULL,
    email      varchar(100)                                      NOT NULL,
    pass_hash  varchar(64)                                       NOT NULL
);

-- A prototype of a subject
CREATE TABLE IF NOT EXISTS subjects
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE NOT NULL,
    name        varchar(255)                                             NOT NULL,
    teacher_ids uuid[]
);

-- A single class/group
CREATE TABLE IF NOT EXISTS groups
(
    id                int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE NOT NULL,
    name              varchar(255)                                             NOT NULL,
    leader_teacher_id uuid                                                     NOT NULL,
    FOREIGN KEY (leader_teacher_id) REFERENCES teachers (id),
    students_ids      uuid[]                                                   NOT NULL
);

-- Schedule for a single school day of a class
CREATE TABLE IF NOT EXISTS schedules
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE NOT NULL,
    group_id    int8                                                     NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (id),
    day_of_week int2                                                     NOT NULL,
    CHECK (day_of_week >= 0 AND day_of_week <= 7),
    subjects    int8[]                                                   NOT NULL
);

-- A single given homework
CREATE TABLE IF NOT EXISTS homeworks
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    is_none     bool          DEFAULT true,
    summary     varchar(1024) DEFAULT NULL,
    teacher_id  uuid                                                     NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES teachers (id),
    attachments int8[]                                                   NOT NULL
);

-- A single lesson instance
CREATE TABLE IF NOT EXISTS lessons
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE NOT NULL,
    subject_id  int8                                                     NOT NULL,
    FOREIGN KEY (subject_id) REFERENCES subjects (id),
    marks       int8[]                                                   NOT NULL,
    homework_id int8                                                     NOT NULL,
    FOREIGN KEY (homework_id) REFERENCES homeworks (id),
    day         date                                                     NOT NULL
);

-- A single given mark
CREATE TABLE IF NOT EXISTS marks
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE NOT NULL,
    value      int2                                                     NOT NULL,
    idx        int2                                                     NOT NULL,
    lesson_id  int8                                                     NOT NULL,
    FOREIGN KEY (lesson_id) REFERENCES lessons (id),
    CHECK (idx BETWEEN 1 AND 5),
    kind       varchar(64)                                              NOT NULL DEFAULT 'GENERIC',
    student_id uuid                                                     NOT NULL,
    FOREIGN KEY (student_id) REFERENCES students (id),
    teacher_id uuid                                                     NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES teachers (id)
);

-- A single attachment
CREATE TABLE IF NOT EXISTS attachments
(
    id        int8 GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    file_name varchar(255)                                             NOT NULL
);